### ISSUE TITLE
Can't play since the update

### ISSUE THREAD

**Issue by Bajal45** [blackspider9678/Tier-of-the-Witchcraft#1]
Like other big modpack (like all the mods 3 remix or ragnamod V) that have +200 mods in it the game crash when enter a solo world.

Latest log, it don't creat any crash report file 
[latest.log](https://github.com/blackspider9678/Tier-of-the-Witchcraft/files/3638497/latest.log)

**Comment by blackspider9678** [comment]
So I looked at the latest.log file and it doesn't even tell me how it crashed other than that a dimension didn't load correctly. May I ask what you did to try to fix loading a world, so that I know.

**Comment by Bajal45** [comment]
I just create a new world and play for 20 minutes and didn't have any issue.
I don't undersand why but it seems to work.

**Comment by blackspider9678** [comment]
hmm, ok. Well good to know, let me know if it happens again.
